//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class PositionServiceRequest : Message
    {
        public const string RosMessageName = "robotics_demo/PositionService";

        public PosRot input;

        public PositionServiceRequest()
        {
            this.input = new PosRot();
        }

        public PositionServiceRequest(PosRot input)
        {
            this.input = input;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(input.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.input.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "PositionServiceRequest: " +
            "\ninput: " + input.ToString();
        }
    }
}
