//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class RobotTrajectory : Message
    {
        public const string RosMessageName = "moveit_msgs/RobotTrajectory";

        public Trajectory.JointTrajectory joint_trajectory;
        public Trajectory.MultiDOFJointTrajectory multi_dof_joint_trajectory;

        public RobotTrajectory()
        {
            this.joint_trajectory = new Trajectory.JointTrajectory();
            this.multi_dof_joint_trajectory = new Trajectory.MultiDOFJointTrajectory();
        }

        public RobotTrajectory(Trajectory.JointTrajectory joint_trajectory, Trajectory.MultiDOFJointTrajectory multi_dof_joint_trajectory)
        {
            this.joint_trajectory = joint_trajectory;
            this.multi_dof_joint_trajectory = multi_dof_joint_trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joint_trajectory.SerializationStatements());
            listOfSerializations.AddRange(multi_dof_joint_trajectory.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joint_trajectory.Deserialize(data, offset);
            offset = this.multi_dof_joint_trajectory.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "RobotTrajectory: " +
            "\njoint_trajectory: " + joint_trajectory.ToString() +
            "\nmulti_dof_joint_trajectory: " + multi_dof_joint_trajectory.ToString();
        }
    }
}
