//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class AllowedCollisionEntryMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/AllowedCollisionEntry";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  whether or not collision checking is enabled
        public bool[] enabled;

        public AllowedCollisionEntryMsg()
        {
            this.enabled = new bool[0];
        }

        public AllowedCollisionEntryMsg(bool[] enabled)
        {
            this.enabled = enabled;
        }

        static string[] s_FieldNames = { "enabled" };

        public static AllowedCollisionEntryMsg Deserialize(IMessageDeserializer deserializer) => new AllowedCollisionEntryMsg(deserializer);

        private AllowedCollisionEntryMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.enabled);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.enabled);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "AllowedCollisionEntryMsg: " +
            "\nenabled: " + System.String.Join(", ", enabled.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
