//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class BoundingVolumeMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/BoundingVolume";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  Define a volume in 3D
        //  A set of solid geometric primitives that make up the volume to define (as a union)
        public ShapeMessages.SolidPrimitiveMsg[] primitives;
        //  The poses at which the primitives are located
        public GeometryMessages.PoseMsg[] primitive_poses;
        //  In addition to primitives, meshes can be specified to add to the bounding volume (again, as union)
        public ShapeMessages.MeshMsg[] meshes;
        //  The poses at which the meshes are located
        public GeometryMessages.PoseMsg[] mesh_poses;

        public BoundingVolumeMsg()
        {
            this.primitives = new ShapeMessages.SolidPrimitiveMsg[0];
            this.primitive_poses = new GeometryMessages.PoseMsg[0];
            this.meshes = new ShapeMessages.MeshMsg[0];
            this.mesh_poses = new GeometryMessages.PoseMsg[0];
        }

        public BoundingVolumeMsg(ShapeMessages.SolidPrimitiveMsg[] primitives, GeometryMessages.PoseMsg[] primitive_poses, ShapeMessages.MeshMsg[] meshes, GeometryMessages.PoseMsg[] mesh_poses)
        {
            this.primitives = primitives;
            this.primitive_poses = primitive_poses;
            this.meshes = meshes;
            this.mesh_poses = mesh_poses;
        }

        static string[] s_FieldNames = { "primitives", "primitive_poses", "meshes", "mesh_poses" };

        public static BoundingVolumeMsg Deserialize(IMessageDeserializer deserializer) => new BoundingVolumeMsg(deserializer);

        private BoundingVolumeMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.primitives);
            deserializer.Read(out this.primitive_poses);
            deserializer.Read(out this.meshes);
            deserializer.Read(out this.mesh_poses);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.primitives);
            serializer.Write(this.primitive_poses);
            serializer.Write(this.meshes);
            serializer.Write(this.mesh_poses);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "BoundingVolumeMsg: " +
            "\nprimitives: " + System.String.Join(", ", primitives.ToList()) +
            "\nprimitive_poses: " + System.String.Join(", ", primitive_poses.ToList()) +
            "\nmeshes: " + System.String.Join(", ", meshes.ToList()) +
            "\nmesh_poses: " + System.String.Join(", ", mesh_poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
