//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class CartesianPointMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/CartesianPoint";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message defines a point in a cartesian trajectory
        public GeometryMessages.PoseMsg pose;
        public GeometryMessages.TwistMsg velocity;
        public GeometryMessages.AccelMsg acceleration;

        public CartesianPointMsg()
        {
            this.pose = new GeometryMessages.PoseMsg();
            this.velocity = new GeometryMessages.TwistMsg();
            this.acceleration = new GeometryMessages.AccelMsg();
        }

        public CartesianPointMsg(GeometryMessages.PoseMsg pose, GeometryMessages.TwistMsg velocity, GeometryMessages.AccelMsg acceleration)
        {
            this.pose = pose;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }

        static string[] s_FieldNames = { "pose", "velocity", "acceleration" };

        public static CartesianPointMsg Deserialize(IMessageDeserializer deserializer) => new CartesianPointMsg(deserializer);

        private CartesianPointMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.pose);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.acceleration);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.pose);
            serializer.Write(this.velocity);
            serializer.Write(this.acceleration);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "CartesianPointMsg: " +
            "\npose: " + pose.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
