//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class CartesianTrajectoryPointMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/CartesianTrajectoryPoint";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The definition of a cartesian point in a trajectory. Defines the cartesian state of the point and it's time,
        //  following the pattern of the JointTrajectory message
        public CartesianPointMsg point;
        public BuiltinInterfacesMessages.DurationMsg time_from_start;

        public CartesianTrajectoryPointMsg()
        {
            this.point = new CartesianPointMsg();
            this.time_from_start = new BuiltinInterfacesMessages.DurationMsg();
        }

        public CartesianTrajectoryPointMsg(CartesianPointMsg point, BuiltinInterfacesMessages.DurationMsg time_from_start)
        {
            this.point = point;
            this.time_from_start = time_from_start;
        }

        static string[] s_FieldNames = { "point", "time_from_start" };

        public static CartesianTrajectoryPointMsg Deserialize(IMessageDeserializer deserializer) => new CartesianTrajectoryPointMsg(deserializer);

        private CartesianTrajectoryPointMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.point);
            deserializer.Read(out this.time_from_start);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.point);
            serializer.Write(this.time_from_start);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "CartesianTrajectoryPointMsg: " +
            "\npoint: " + point.ToString() +
            "\ntime_from_start: " + time_from_start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
