//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class CartesianTrajectoryMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/CartesianTrajectory";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message describes the trajectory of a tracked frame in task-space
        public StdMessages.HeaderMsg header;
        //  The name of the Cartesian frame being tracked with respect to the base frame provided in header.frame_id
        public string tracked_frame;
        public CartesianTrajectoryPointMsg[] points;

        public CartesianTrajectoryMsg()
        {
            this.header = new StdMessages.HeaderMsg();
            this.tracked_frame = "";
            this.points = new CartesianTrajectoryPointMsg[0];
        }

        public CartesianTrajectoryMsg(StdMessages.HeaderMsg header, string tracked_frame, CartesianTrajectoryPointMsg[] points)
        {
            this.header = header;
            this.tracked_frame = tracked_frame;
            this.points = points;
        }

        static string[] s_FieldNames = { "header", "tracked_frame", "points" };

        public static CartesianTrajectoryMsg Deserialize(IMessageDeserializer deserializer) => new CartesianTrajectoryMsg(deserializer);

        private CartesianTrajectoryMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.header);
            deserializer.Read(out this.tracked_frame);
            deserializer.Read(out this.points);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.header);
            serializer.Write(this.tracked_frame);
            serializer.Write(this.points);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "CartesianTrajectoryMsg: " +
            "\nheader: " + header.ToString() +
            "\ntracked_frame: " + tracked_frame.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
