//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class ConstraintEvalResultMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/ConstraintEvalResult";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message contains result from constraint evaluation
        //  result specifies the result of constraint evaluation
        //  (true indicates state satisfies constraint, false indicates state violates constraint)
        //  if false, distance specifies a measure of the distance of the state from the constraint
        //  if true, distance is set to zero
        public bool result;
        public double distance;

        public ConstraintEvalResultMsg()
        {
            this.result = false;
            this.distance = 0.0;
        }

        public ConstraintEvalResultMsg(bool result, double distance)
        {
            this.result = result;
            this.distance = distance;
        }

        static string[] s_FieldNames = { "result", "distance" };

        public static ConstraintEvalResultMsg Deserialize(IMessageDeserializer deserializer) => new ConstraintEvalResultMsg(deserializer);

        private ConstraintEvalResultMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.result);
            deserializer.Read(out this.distance);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.result);
            serializer.Write(this.distance);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "ConstraintEvalResultMsg: " +
            "\nresult: " + result.ToString() +
            "\ndistance: " + distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
