//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class ConstraintsMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/Constraints";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message contains a list of motion planning constraints.
        //  All constraints must be satisfied for a goal to be considered valid
        public string name;
        public JointConstraintMsg[] joint_constraints;
        public PositionConstraintMsg[] position_constraints;
        public OrientationConstraintMsg[] orientation_constraints;
        public VisibilityConstraintMsg[] visibility_constraints;

        public ConstraintsMsg()
        {
            this.name = "";
            this.joint_constraints = new JointConstraintMsg[0];
            this.position_constraints = new PositionConstraintMsg[0];
            this.orientation_constraints = new OrientationConstraintMsg[0];
            this.visibility_constraints = new VisibilityConstraintMsg[0];
        }

        public ConstraintsMsg(string name, JointConstraintMsg[] joint_constraints, PositionConstraintMsg[] position_constraints, OrientationConstraintMsg[] orientation_constraints, VisibilityConstraintMsg[] visibility_constraints)
        {
            this.name = name;
            this.joint_constraints = joint_constraints;
            this.position_constraints = position_constraints;
            this.orientation_constraints = orientation_constraints;
            this.visibility_constraints = visibility_constraints;
        }

        static string[] s_FieldNames = { "name", "joint_constraints", "position_constraints", 
            "orientation_constraints", "visibility_constraints" };

        public static ConstraintsMsg Deserialize(IMessageDeserializer deserializer) => new ConstraintsMsg(deserializer);

        private ConstraintsMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.name);
            deserializer.Read(out this.joint_constraints);
            deserializer.Read(out this.position_constraints);
            deserializer.Read(out this.orientation_constraints);
            deserializer.Read(out this.visibility_constraints);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.name);
            serializer.Write(this.joint_constraints);
            serializer.Write(this.position_constraints);
            serializer.Write(this.orientation_constraints);
            serializer.Write(this.visibility_constraints);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "ConstraintsMsg: " +
            "\nname: " + name.ToString() +
            "\njoint_constraints: " + System.String.Join(", ", joint_constraints.ToList()) +
            "\nposition_constraints: " + System.String.Join(", ", position_constraints.ToList()) +
            "\norientation_constraints: " + System.String.Join(", ", orientation_constraints.ToList()) +
            "\nvisibility_constraints: " + System.String.Join(", ", visibility_constraints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
