//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class DisplayRobotStateMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/DisplayRobotState";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The robot state to display
        public RobotStateMsg state;
        //  Optionally, various links can be highlighted
        public ObjectColorMsg[] highlight_links;
        //  If true, suppress the display in visualizations (like rviz)
        public bool hide;

        public DisplayRobotStateMsg()
        {
            this.state = new RobotStateMsg();
            this.highlight_links = new ObjectColorMsg[0];
            this.hide = false;
        }

        public DisplayRobotStateMsg(RobotStateMsg state, ObjectColorMsg[] highlight_links, bool hide)
        {
            this.state = state;
            this.highlight_links = highlight_links;
            this.hide = hide;
        }

        static string[] s_FieldNames = { "state", "highlight_links", "hide" };

        public static DisplayRobotStateMsg Deserialize(IMessageDeserializer deserializer) => new DisplayRobotStateMsg(deserializer);

        private DisplayRobotStateMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.state);
            deserializer.Read(out this.highlight_links);
            deserializer.Read(out this.hide);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.state);
            serializer.Write(this.highlight_links);
            serializer.Write(this.hide);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "DisplayRobotStateMsg: " +
            "\nstate: " + state.ToString() +
            "\nhighlight_links: " + System.String.Join(", ", highlight_links.ToList()) +
            "\nhide: " + hide.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
