//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class DisplayTrajectoryMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/DisplayTrajectory";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The model id for which this path has been generated
        public string model_id;
        //  The representation of the path contains position values for all the joints that are moving along the path;
        //  a sequence of trajectories may be specified
        public RobotTrajectoryMsg[] trajectory;
        //  The robot state is used to obtain positions for all/some of the joints of the robot.
        //  It is used by the path display node to determine the positions of the joints that are not specified
        //  in the joint trajectory message above. The positions in the joint trajectory message
        //  take precedence (for joints that the message covers).
        public RobotStateMsg trajectory_start;

        public DisplayTrajectoryMsg()
        {
            this.model_id = "";
            this.trajectory = new RobotTrajectoryMsg[0];
            this.trajectory_start = new RobotStateMsg();
        }

        public DisplayTrajectoryMsg(string model_id, RobotTrajectoryMsg[] trajectory, RobotStateMsg trajectory_start)
        {
            this.model_id = model_id;
            this.trajectory = trajectory;
            this.trajectory_start = trajectory_start;
        }

        static string[] s_FieldNames = { "model_id", "trajectory", "trajectory_start" };

        public static DisplayTrajectoryMsg Deserialize(IMessageDeserializer deserializer) => new DisplayTrajectoryMsg(deserializer);

        private DisplayTrajectoryMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.model_id);
            deserializer.Read(out this.trajectory);
            deserializer.Read(out this.trajectory_start);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.model_id);
            serializer.Write(this.trajectory);
            serializer.Write(this.trajectory_start);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "DisplayTrajectoryMsg: " +
            "\nmodel_id: " + model_id.ToString() +
            "\ntrajectory: " + System.String.Join(", ", trajectory.ToList()) +
            "\ntrajectory_start: " + trajectory_start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
