//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class GenericTrajectoryMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/GenericTrajectory";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  A generic trajectory message that may either encode a joint- or cartesian-space trajectory, or both
        //  Trajectories encoded in this message are considered semantically equivalent
        public StdMessages.HeaderMsg header;
        public TrajectoryMessages.JointTrajectoryMsg[] joint_trajectory;
        public CartesianTrajectoryMsg[] cartesian_trajectory;

        public GenericTrajectoryMsg()
        {
            this.header = new StdMessages.HeaderMsg();
            this.joint_trajectory = new TrajectoryMessages.JointTrajectoryMsg[0];
            this.cartesian_trajectory = new CartesianTrajectoryMsg[0];
        }

        public GenericTrajectoryMsg(StdMessages.HeaderMsg header, TrajectoryMessages.JointTrajectoryMsg[] joint_trajectory, CartesianTrajectoryMsg[] cartesian_trajectory)
        {
            this.header = header;
            this.joint_trajectory = joint_trajectory;
            this.cartesian_trajectory = cartesian_trajectory;
        }

        static string[] s_FieldNames = { "header", "joint_trajectory", "cartesian_trajectory" };

        public static GenericTrajectoryMsg Deserialize(IMessageDeserializer deserializer) => new GenericTrajectoryMsg(deserializer);

        private GenericTrajectoryMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.header);
            deserializer.Read(out this.joint_trajectory);
            deserializer.Read(out this.cartesian_trajectory);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.header);
            serializer.Write(this.joint_trajectory);
            serializer.Write(this.cartesian_trajectory);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "GenericTrajectoryMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_trajectory: " + System.String.Join(", ", joint_trajectory.ToList()) +
            "\ncartesian_trajectory: " + System.String.Join(", ", cartesian_trajectory.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
