//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class GripperTranslationMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/GripperTranslation";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  defines a translation for the gripper, used in pickup or place tasks
        //  for example for lifting an object off a table or approaching the table for placing
        //  the direction of the translation
        public GeometryMessages.Vector3StampedMsg direction;
        //  the desired translation distance
        public float desired_distance;
        //  the min distance that must be considered feasible before the
        //  grasp is even attempted
        public float min_distance;

        public GripperTranslationMsg()
        {
            this.direction = new GeometryMessages.Vector3StampedMsg();
            this.desired_distance = 0.0f;
            this.min_distance = 0.0f;
        }

        public GripperTranslationMsg(GeometryMessages.Vector3StampedMsg direction, float desired_distance, float min_distance)
        {
            this.direction = direction;
            this.desired_distance = desired_distance;
            this.min_distance = min_distance;
        }

        static string[] s_FieldNames = { "direction", "desired_distance", "min_distance" };

        public static GripperTranslationMsg Deserialize(IMessageDeserializer deserializer) => new GripperTranslationMsg(deserializer);

        private GripperTranslationMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.direction);
            deserializer.Read(out this.desired_distance);
            deserializer.Read(out this.min_distance);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.direction);
            serializer.Write(this.desired_distance);
            serializer.Write(this.min_distance);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "GripperTranslationMsg: " +
            "\ndirection: " + direction.ToString() +
            "\ndesired_distance: " + desired_distance.ToString() +
            "\nmin_distance: " + min_distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
