//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class KinematicSolverInfoMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/KinematicSolverInfo";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  A list of joints in the kinematic tree
        public string[] joint_names;
        //  A list of joint limits corresponding to the joint names
        public JointLimitsMsg[] limits;
        //  A list of links that the kinematics node provides solutions for
        public string[] link_names;

        public KinematicSolverInfoMsg()
        {
            this.joint_names = new string[0];
            this.limits = new JointLimitsMsg[0];
            this.link_names = new string[0];
        }

        public KinematicSolverInfoMsg(string[] joint_names, JointLimitsMsg[] limits, string[] link_names)
        {
            this.joint_names = joint_names;
            this.limits = limits;
            this.link_names = link_names;
        }

        static string[] s_FieldNames = { "joint_names", "limits", "link_names" };

        public static KinematicSolverInfoMsg Deserialize(IMessageDeserializer deserializer) => new KinematicSolverInfoMsg(deserializer);

        private KinematicSolverInfoMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.joint_names);
            deserializer.Read(out this.limits);
            deserializer.Read(out this.link_names);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.joint_names);
            serializer.Write(this.limits);
            serializer.Write(this.link_names);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "KinematicSolverInfoMsg: " +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\nlimits: " + System.String.Join(", ", limits.ToList()) +
            "\nlink_names: " + System.String.Join(", ", link_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
