//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class LinkScaleMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/LinkScale";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        // name for the link
        public string link_name;
        //  scaling to apply to the link
        public double scale;

        public LinkScaleMsg()
        {
            this.link_name = "";
            this.scale = 0.0;
        }

        public LinkScaleMsg(string link_name, double scale)
        {
            this.link_name = link_name;
            this.scale = scale;
        }

        static string[] s_FieldNames = { "link_name", "scale" };

        public static LinkScaleMsg Deserialize(IMessageDeserializer deserializer) => new LinkScaleMsg(deserializer);

        private LinkScaleMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.scale);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.link_name);
            serializer.Write(this.scale);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "LinkScaleMsg: " +
            "\nlink_name: " + link_name.ToString() +
            "\nscale: " + scale.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
