//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class LinkPaddingMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/LinkPadding";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        // name for the link
        public string link_name;
        //  padding to apply to the link
        public double padding;

        public LinkPaddingMsg()
        {
            this.link_name = "";
            this.padding = 0.0;
        }

        public LinkPaddingMsg(string link_name, double padding)
        {
            this.link_name = link_name;
            this.padding = padding;
        }

        static string[] s_FieldNames = { "link_name", "padding" };

        public static LinkPaddingMsg Deserialize(IMessageDeserializer deserializer) => new LinkPaddingMsg(deserializer);

        private LinkPaddingMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.padding);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.link_name);
            serializer.Write(this.padding);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "LinkPaddingMsg: " +
            "\nlink_name: " + link_name.ToString() +
            "\npadding: " + padding.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
