//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MotionPlanResponseMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MotionPlanResponse";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The representation of a solution to a planning problem
        //  The corresponding robot state
        public RobotStateMsg trajectory_start;
        //  The group used for planning (usually the same as in the request)
        public string group_name;
        //  A solution trajectory, if found
        public RobotTrajectoryMsg trajectory;
        //  Planning time (seconds)
        public double planning_time;
        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodesMsg error_code;

        public MotionPlanResponseMsg()
        {
            this.trajectory_start = new RobotStateMsg();
            this.group_name = "";
            this.trajectory = new RobotTrajectoryMsg();
            this.planning_time = 0.0;
            this.error_code = new MoveItErrorCodesMsg();
        }

        public MotionPlanResponseMsg(RobotStateMsg trajectory_start, string group_name, RobotTrajectoryMsg trajectory, double planning_time, MoveItErrorCodesMsg error_code)
        {
            this.trajectory_start = trajectory_start;
            this.group_name = group_name;
            this.trajectory = trajectory;
            this.planning_time = planning_time;
            this.error_code = error_code;
        }

        static string[] s_FieldNames = { "trajectory_start", "group_name", "trajectory", 
            "planning_time", "error_code" };

        public static MotionPlanResponseMsg Deserialize(IMessageDeserializer deserializer) => new MotionPlanResponseMsg(deserializer);

        private MotionPlanResponseMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.trajectory_start);
            deserializer.Read(out this.group_name);
            deserializer.Read(out this.trajectory);
            deserializer.Read(out this.planning_time);
            deserializer.Read(out this.error_code);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.trajectory_start);
            serializer.Write(this.group_name);
            serializer.Write(this.trajectory);
            serializer.Write(this.planning_time);
            serializer.Write(this.error_code);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MotionPlanResponseMsg: " +
            "\ntrajectory_start: " + trajectory_start.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\ntrajectory: " + trajectory.ToString() +
            "\nplanning_time: " + planning_time.ToString() +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
