//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MotionSequenceItemMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MotionSequenceItem";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The plan request for this item.
        //  It is the planning request for this segment of the sequence, as if it were a solitary motion.
        public MotionPlanRequestMsg req;
        //  To blend between sequence items, the motion may be smoothed using a circular motion.
        //  The blend radius of the circle between this and the next command, where 0 means no blending.
        public double blend_radius;

        public MotionSequenceItemMsg()
        {
            this.req = new MotionPlanRequestMsg();
            this.blend_radius = 0.0;
        }

        public MotionSequenceItemMsg(MotionPlanRequestMsg req, double blend_radius)
        {
            this.req = req;
            this.blend_radius = blend_radius;
        }

        static string[] s_FieldNames = { "req", "blend_radius" };

        public static MotionSequenceItemMsg Deserialize(IMessageDeserializer deserializer) => new MotionSequenceItemMsg(deserializer);

        private MotionSequenceItemMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.req);
            deserializer.Read(out this.blend_radius);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.req);
            serializer.Write(this.blend_radius);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MotionSequenceItemMsg: " +
            "\nreq: " + req.ToString() +
            "\nblend_radius: " + blend_radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
