//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MotionSequenceResponseMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MotionSequenceResponse";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  An error code reflecting what went wrong
        public MoveItErrorCodesMsg error_code;
        //  The full starting state of the robot at the start of the sequence
        public RobotStateMsg sequence_start;
        //  The trajectories that the planner produced for execution
        public RobotTrajectoryMsg[] planned_trajectories;
        //  The amount of time it took to complete the motion plan
        public double planning_time;

        public MotionSequenceResponseMsg()
        {
            this.error_code = new MoveItErrorCodesMsg();
            this.sequence_start = new RobotStateMsg();
            this.planned_trajectories = new RobotTrajectoryMsg[0];
            this.planning_time = 0.0;
        }

        public MotionSequenceResponseMsg(MoveItErrorCodesMsg error_code, RobotStateMsg sequence_start, RobotTrajectoryMsg[] planned_trajectories, double planning_time)
        {
            this.error_code = error_code;
            this.sequence_start = sequence_start;
            this.planned_trajectories = planned_trajectories;
            this.planning_time = planning_time;
        }

        static string[] s_FieldNames = { "error_code", "sequence_start", "planned_trajectories", 
            "planning_time" };

        public static MotionSequenceResponseMsg Deserialize(IMessageDeserializer deserializer) => new MotionSequenceResponseMsg(deserializer);

        private MotionSequenceResponseMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.error_code);
            deserializer.Read(out this.sequence_start);
            deserializer.Read(out this.planned_trajectories);
            deserializer.Read(out this.planning_time);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.error_code);
            serializer.Write(this.sequence_start);
            serializer.Write(this.planned_trajectories);
            serializer.Write(this.planning_time);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MotionSequenceResponseMsg: " +
            "\nerror_code: " + error_code.ToString() +
            "\nsequence_start: " + sequence_start.ToString() +
            "\nplanned_trajectories: " + System.String.Join(", ", planned_trajectories.ToList()) +
            "\nplanning_time: " + planning_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
