//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MotionPlanDetailedResponseMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MotionPlanDetailedResponse";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The representation of a solution to a planning problem, including intermediate data
        //  The starting state considered for the robot solution path
        public RobotStateMsg trajectory_start;
        //  The group used for planning (usually the same as in the request)
        public string group_name;
        //  Multiple solution paths are reported, each reflecting intermediate steps in the trajectory processing
        //  The list of reported trajectories
        public RobotTrajectoryMsg[] trajectory;
        //  Description of the reported trajectories (name of processing step)
        public string[] description;
        //  The amount of time spent computing a particular step in motion plan computation
        public double[] processing_time;
        //  Status at the end of this plan
        public MoveItErrorCodesMsg error_code;

        public MotionPlanDetailedResponseMsg()
        {
            this.trajectory_start = new RobotStateMsg();
            this.group_name = "";
            this.trajectory = new RobotTrajectoryMsg[0];
            this.description = new string[0];
            this.processing_time = new double[0];
            this.error_code = new MoveItErrorCodesMsg();
        }

        public MotionPlanDetailedResponseMsg(RobotStateMsg trajectory_start, string group_name, RobotTrajectoryMsg[] trajectory, string[] description, double[] processing_time, MoveItErrorCodesMsg error_code)
        {
            this.trajectory_start = trajectory_start;
            this.group_name = group_name;
            this.trajectory = trajectory;
            this.description = description;
            this.processing_time = processing_time;
            this.error_code = error_code;
        }

        static string[] s_FieldNames = { "trajectory_start", "group_name", "trajectory", "description", 
            "processing_time", "error_code" };

        public static MotionPlanDetailedResponseMsg Deserialize(IMessageDeserializer deserializer) => new MotionPlanDetailedResponseMsg(deserializer);

        private MotionPlanDetailedResponseMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.trajectory_start);
            deserializer.Read(out this.group_name);
            deserializer.Read(out this.trajectory);
            deserializer.Read(out this.description);
            deserializer.Read(out this.processing_time);
            deserializer.Read(out this.error_code);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.trajectory_start);
            serializer.Write(this.group_name);
            serializer.Write(this.trajectory);
            serializer.Write(this.description);
            serializer.Write(this.processing_time);
            serializer.Write(this.error_code);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MotionPlanDetailedResponseMsg: " +
            "\ntrajectory_start: " + trajectory_start.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\ntrajectory: " + System.String.Join(", ", trajectory.ToList()) +
            "\ndescription: " + System.String.Join(", ", description.ToList()) +
            "\nprocessing_time: " + System.String.Join(", ", processing_time.ToList()) +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
