//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MotionSequenceRequestMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MotionSequenceRequest";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  List of motion planning request with a blend_radius for each.
        //  In the response of the planner all of these will be executable as one sequence.
        public MotionSequenceItemMsg[] items;

        public MotionSequenceRequestMsg()
        {
            this.items = new MotionSequenceItemMsg[0];
        }

        public MotionSequenceRequestMsg(MotionSequenceItemMsg[] items)
        {
            this.items = items;
        }

        static string[] s_FieldNames = { "items" };

        public static MotionSequenceRequestMsg Deserialize(IMessageDeserializer deserializer) => new MotionSequenceRequestMsg(deserializer);

        private MotionSequenceRequestMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.items);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.items);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MotionSequenceRequestMsg: " +
            "\nitems: " + System.String.Join(", ", items.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
