//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class MoveItErrorCodesMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/MoveItErrorCodes";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        public int val;
        //  overall behavior
        public const int SUCCESS = 1;
        public const int UNDEFINED = 0;
        public const int FAILURE = 99999;
        public const int PLANNING_FAILED = -1;
        public const int INVALID_MOTION_PLAN = -2;
        public const int MOTION_PLAN_INVALIDATED_BY_ENVIRONMENT_CHANGE = -3;
        public const int CONTROL_FAILED = -4;
        public const int UNABLE_TO_AQUIRE_SENSOR_DATA = -5;
        public const int TIMED_OUT = -6;
        public const int PREEMPTED = -7;
        //  planning & kinematics request errors
        public const int START_STATE_IN_COLLISION = -10;
        public const int START_STATE_VIOLATES_PATH_CONSTRAINTS = -11;
        public const int START_STATE_INVALID = -26;
        public const int GOAL_IN_COLLISION = -12;
        public const int GOAL_VIOLATES_PATH_CONSTRAINTS = -13;
        public const int GOAL_CONSTRAINTS_VIOLATED = -14;
        public const int GOAL_STATE_INVALID = -27;
        public const int UNRECOGNIZED_GOAL_TYPE = -28;
        public const int INVALID_GROUP_NAME = -15;
        public const int INVALID_GOAL_CONSTRAINTS = -16;
        public const int INVALID_ROBOT_STATE = -17;
        public const int INVALID_LINK_NAME = -18;
        public const int INVALID_OBJECT_NAME = -19;
        //  system errors
        public const int FRAME_TRANSFORM_FAILURE = -21;
        public const int COLLISION_CHECKING_UNAVAILABLE = -22;
        public const int ROBOT_STATE_STALE = -23;
        public const int SENSOR_INFO_STALE = -24;
        public const int COMMUNICATION_FAILURE = -25;
        public const int CRASH = -29;
        public const int ABORT = -30;
        //  kinematics errors
        public const int NO_IK_SOLUTION = -31;
        //  A message to provide additional information.
        public string message;
        //  Name of the component that created the status.
        //  This is helpful to locate error source.
        public string source;

        public MoveItErrorCodesMsg()
        {
            this.val = 0;
            this.message = "";
            this.source = "";
        }

        public MoveItErrorCodesMsg(int val, string message, string source)
        {
            this.val = val;
            this.message = message;
            this.source = source;
        }

        static string[] s_FieldNames = { "val", "message", "source" };

        public static MoveItErrorCodesMsg Deserialize(IMessageDeserializer deserializer) => new MoveItErrorCodesMsg(deserializer);

        private MoveItErrorCodesMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.val);
            deserializer.Read(out this.message);
            deserializer.Read(out this.source);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.val);
            serializer.Write(this.message);
            serializer.Write(this.source);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MoveItErrorCodesMsg: " +
            "\nval: " + val.ToString() +
            "\nmessage: " + message.ToString() +
            "\nsource: " + source.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
