//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class ObjectColorMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/ObjectColor";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The object id for which we specify color
        public string id;
        //  The value of the color
        public StdMessages.ColorRGBAMsg color;

        public ObjectColorMsg()
        {
            this.id = "";
            this.color = new StdMessages.ColorRGBAMsg();
        }

        public ObjectColorMsg(string id, StdMessages.ColorRGBAMsg color)
        {
            this.id = id;
            this.color = color;
        }

        static string[] s_FieldNames = { "id", "color" };

        public static ObjectColorMsg Deserialize(IMessageDeserializer deserializer) => new ObjectColorMsg(deserializer);

        private ObjectColorMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.id);
            deserializer.Read(out this.color);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.id);
            serializer.Write(this.color);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "ObjectColorMsg: " +
            "\nid: " + id.ToString() +
            "\ncolor: " + color.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
