//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class OrientedBoundingBoxMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/OrientedBoundingBox";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  the pose of the box
        public GeometryMessages.PoseMsg pose;
        //  the extents of the box, assuming the center is at the origin
        public GeometryMessages.Point32Msg extents;

        public OrientedBoundingBoxMsg()
        {
            this.pose = new GeometryMessages.PoseMsg();
            this.extents = new GeometryMessages.Point32Msg();
        }

        public OrientedBoundingBoxMsg(GeometryMessages.PoseMsg pose, GeometryMessages.Point32Msg extents)
        {
            this.pose = pose;
            this.extents = extents;
        }

        static string[] s_FieldNames = { "pose", "extents" };

        public static OrientedBoundingBoxMsg Deserialize(IMessageDeserializer deserializer) => new OrientedBoundingBoxMsg(deserializer);

        private OrientedBoundingBoxMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.pose);
            deserializer.Read(out this.extents);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.pose);
            serializer.Write(this.extents);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "OrientedBoundingBoxMsg: " +
            "\npose: " + pose.ToString() +
            "\nextents: " + extents.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
