//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class OrientationConstraintMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/OrientationConstraint";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message contains the definition of an orientation constraint.
        public StdMessages.HeaderMsg header;
        //  The desired orientation of the robot link specified as a quaternion
        public GeometryMessages.QuaternionMsg orientation;
        //  The robot link this constraint refers to
        public string link_name;
        //  Tolerance on the three vector components of the orientation error (optional)
        //  This is a +/- tolerance i.e. (+ x_axis_tol, - x_axis_tol)
        public double absolute_x_axis_tolerance;
        public double absolute_y_axis_tolerance;
        public double absolute_z_axis_tolerance;
        //  Defines how the orientation error is calculated
        //  The error is compared to the tolerance defined above
        public byte parameterization;
        //  The different options for the orientation error parameterization
        //  - Intrinsic xyz Euler angles (default value)
        public const byte XYZ_EULER_ANGLES = 0;
        //  - A rotation vector. This is similar to the angle-axis representation,
        //  but the magnitude of the vector represents the rotation angle.
        public const byte ROTATION_VECTOR = 1;
        //  A weighting factor for this constraint (denotes relative importance to other constraints. Closer to zero means less important)
        public double weight;

        public OrientationConstraintMsg()
        {
            this.header = new StdMessages.HeaderMsg();
            this.orientation = new GeometryMessages.QuaternionMsg();
            this.link_name = "";
            this.absolute_x_axis_tolerance = 0.0;
            this.absolute_y_axis_tolerance = 0.0;
            this.absolute_z_axis_tolerance = 0.0;
            this.parameterization = 0;
            this.weight = 0.0;
        }

        public OrientationConstraintMsg(StdMessages.HeaderMsg header, GeometryMessages.QuaternionMsg orientation, string link_name, double absolute_x_axis_tolerance, double absolute_y_axis_tolerance, double absolute_z_axis_tolerance, byte parameterization, double weight)
        {
            this.header = header;
            this.orientation = orientation;
            this.link_name = link_name;
            this.absolute_x_axis_tolerance = absolute_x_axis_tolerance;
            this.absolute_y_axis_tolerance = absolute_y_axis_tolerance;
            this.absolute_z_axis_tolerance = absolute_z_axis_tolerance;
            this.parameterization = parameterization;
            this.weight = weight;
        }

        static string[] s_FieldNames = { "header", "orientation", "link_name", 
            "absolute_x_axis_tolerance", "absolute_y_axis_tolerance", "absolute_z_axis_tolerance", 
            "parameterization", "weight" };

        public static OrientationConstraintMsg Deserialize(IMessageDeserializer deserializer) => new OrientationConstraintMsg(deserializer);

        private OrientationConstraintMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.header);
            deserializer.Read(out this.orientation);
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.absolute_x_axis_tolerance);
            deserializer.Read(out this.absolute_y_axis_tolerance);
            deserializer.Read(out this.absolute_z_axis_tolerance);
            deserializer.Read(out this.parameterization);
            deserializer.Read(out this.weight);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.header);
            serializer.Write(this.orientation);
            serializer.Write(this.link_name);
            serializer.Write(this.absolute_x_axis_tolerance);
            serializer.Write(this.absolute_y_axis_tolerance);
            serializer.Write(this.absolute_z_axis_tolerance);
            serializer.Write(this.parameterization);
            serializer.Write(this.weight);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "OrientationConstraintMsg: " +
            "\nheader: " + header.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nlink_name: " + link_name.ToString() +
            "\nabsolute_x_axis_tolerance: " + absolute_x_axis_tolerance.ToString() +
            "\nabsolute_y_axis_tolerance: " + absolute_y_axis_tolerance.ToString() +
            "\nabsolute_z_axis_tolerance: " + absolute_z_axis_tolerance.ToString() +
            "\nparameterization: " + parameterization.ToString() +
            "\nweight: " + weight.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
