//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PipelineStateMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PipelineState";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  Motion plan response that is processed
        public MotionPlanRequestMsg request;
        //  Current solution
        public MotionPlanResponseMsg response;
        //  Latest stage of the planning pipeline that got invoked
        public string pipeline_stage;

        public PipelineStateMsg()
        {
            this.request = new MotionPlanRequestMsg();
            this.response = new MotionPlanResponseMsg();
            this.pipeline_stage = "";
        }

        public PipelineStateMsg(MotionPlanRequestMsg request, MotionPlanResponseMsg response, string pipeline_stage)
        {
            this.request = request;
            this.response = response;
            this.pipeline_stage = pipeline_stage;
        }

        static string[] s_FieldNames = { "request", "response", "pipeline_stage" };

        public static PipelineStateMsg Deserialize(IMessageDeserializer deserializer) => new PipelineStateMsg(deserializer);

        private PipelineStateMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.request);
            deserializer.Read(out this.response);
            deserializer.Read(out this.pipeline_stage);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.request);
            serializer.Write(this.response);
            serializer.Write(this.pipeline_stage);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PipelineStateMsg: " +
            "\nrequest: " + request.ToString() +
            "\nresponse: " + response.ToString() +
            "\npipeline_stage: " + pipeline_stage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
