//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PlaceLocationMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PlaceLocation";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  A name for this grasp
        public string id;
        //  The internal posture of the hand for the grasp
        //  positions and efforts are used
        public TrajectoryMessages.JointTrajectoryMsg post_place_posture;
        //  The position of the end-effector for the grasp relative to a reference frame
        //  (that is always specified elsewhere, not in this message)
        public GeometryMessages.PoseStampedMsg place_pose;
        //  The estimated probability of success for this place, or some other
        //  measure of how "good" it is.
        public double quality;
        //  The approach motion
        public GripperTranslationMsg pre_place_approach;
        //  The retreat motion
        public GripperTranslationMsg post_place_retreat;
        //  an optional list of obstacles that we have semantic information about
        //  and that can be touched/pushed/moved in the course of grasping
        public string[] allowed_touch_objects;

        public PlaceLocationMsg()
        {
            this.id = "";
            this.post_place_posture = new TrajectoryMessages.JointTrajectoryMsg();
            this.place_pose = new GeometryMessages.PoseStampedMsg();
            this.quality = 0.0;
            this.pre_place_approach = new GripperTranslationMsg();
            this.post_place_retreat = new GripperTranslationMsg();
            this.allowed_touch_objects = new string[0];
        }

        public PlaceLocationMsg(string id, TrajectoryMessages.JointTrajectoryMsg post_place_posture, GeometryMessages.PoseStampedMsg place_pose, double quality, GripperTranslationMsg pre_place_approach, GripperTranslationMsg post_place_retreat, string[] allowed_touch_objects)
        {
            this.id = id;
            this.post_place_posture = post_place_posture;
            this.place_pose = place_pose;
            this.quality = quality;
            this.pre_place_approach = pre_place_approach;
            this.post_place_retreat = post_place_retreat;
            this.allowed_touch_objects = allowed_touch_objects;
        }

        static string[] s_FieldNames = { "id", "post_place_posture", "place_pose", "quality", 
            "pre_place_approach", "post_place_retreat", "allowed_touch_objects" };

        public static PlaceLocationMsg Deserialize(IMessageDeserializer deserializer) => new PlaceLocationMsg(deserializer);

        private PlaceLocationMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.id);
            deserializer.Read(out this.post_place_posture);
            deserializer.Read(out this.place_pose);
            deserializer.Read(out this.quality);
            deserializer.Read(out this.pre_place_approach);
            deserializer.Read(out this.post_place_retreat);
            deserializer.Read(out this.allowed_touch_objects);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.id);
            serializer.Write(this.post_place_posture);
            serializer.Write(this.place_pose);
            serializer.Write(this.quality);
            serializer.Write(this.pre_place_approach);
            serializer.Write(this.post_place_retreat);
            serializer.Write(this.allowed_touch_objects);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PlaceLocationMsg: " +
            "\nid: " + id.ToString() +
            "\npost_place_posture: " + post_place_posture.ToString() +
            "\nplace_pose: " + place_pose.ToString() +
            "\nquality: " + quality.ToString() +
            "\npre_place_approach: " + pre_place_approach.ToString() +
            "\npost_place_retreat: " + post_place_retreat.ToString() +
            "\nallowed_touch_objects: " + System.String.Join(", ", allowed_touch_objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
