//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PlanningSceneWorldMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PlanningSceneWorld";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  collision objects
        public CollisionObjectMsg[] collision_objects;
        //  The octomap that represents additional collision data
        public OctomapMessages.OctomapWithPoseMsg octomap;

        public PlanningSceneWorldMsg()
        {
            this.collision_objects = new CollisionObjectMsg[0];
            this.octomap = new OctomapMessages.OctomapWithPoseMsg();
        }

        public PlanningSceneWorldMsg(CollisionObjectMsg[] collision_objects, OctomapMessages.OctomapWithPoseMsg octomap)
        {
            this.collision_objects = collision_objects;
            this.octomap = octomap;
        }

        static string[] s_FieldNames = { "collision_objects", "octomap" };

        public static PlanningSceneWorldMsg Deserialize(IMessageDeserializer deserializer) => new PlanningSceneWorldMsg(deserializer);

        private PlanningSceneWorldMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.collision_objects);
            deserializer.Read(out this.octomap);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.collision_objects);
            serializer.Write(this.octomap);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PlanningSceneWorldMsg: " +
            "\ncollision_objects: " + System.String.Join(", ", collision_objects.ToList()) +
            "\noctomap: " + octomap.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
