//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PlannerParamsMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PlannerParams";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  parameter names (same size as values)
        public string[] keys;
        //  parameter values (same size as keys)
        public string[] values;
        //  parameter description (can be empty)
        public string[] descriptions;

        public PlannerParamsMsg()
        {
            this.keys = new string[0];
            this.values = new string[0];
            this.descriptions = new string[0];
        }

        public PlannerParamsMsg(string[] keys, string[] values, string[] descriptions)
        {
            this.keys = keys;
            this.values = values;
            this.descriptions = descriptions;
        }

        static string[] s_FieldNames = { "keys", "values", "descriptions" };

        public static PlannerParamsMsg Deserialize(IMessageDeserializer deserializer) => new PlannerParamsMsg(deserializer);

        private PlannerParamsMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.keys);
            deserializer.Read(out this.values);
            deserializer.Read(out this.descriptions);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.keys);
            serializer.Write(this.values);
            serializer.Write(this.descriptions);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PlannerParamsMsg: " +
            "\nkeys: " + System.String.Join(", ", keys.ToList()) +
            "\nvalues: " + System.String.Join(", ", values.ToList()) +
            "\ndescriptions: " + System.String.Join(", ", descriptions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
