//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PlannerInterfaceDescriptionMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PlannerInterfaceDescription";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  The name of the planner interface
        public string name;
        //  The name of the planning pipeline
        public string pipeline_id;
        //  The names of the planner ids within the interface
        public string[] planner_ids;

        public PlannerInterfaceDescriptionMsg()
        {
            this.name = "";
            this.pipeline_id = "";
            this.planner_ids = new string[0];
        }

        public PlannerInterfaceDescriptionMsg(string name, string pipeline_id, string[] planner_ids)
        {
            this.name = name;
            this.pipeline_id = pipeline_id;
            this.planner_ids = planner_ids;
        }

        static string[] s_FieldNames = { "name", "pipeline_id", "planner_ids" };

        public static PlannerInterfaceDescriptionMsg Deserialize(IMessageDeserializer deserializer) => new PlannerInterfaceDescriptionMsg(deserializer);

        private PlannerInterfaceDescriptionMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.name);
            deserializer.Read(out this.pipeline_id);
            deserializer.Read(out this.planner_ids);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.name);
            serializer.Write(this.pipeline_id);
            serializer.Write(this.planner_ids);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PlannerInterfaceDescriptionMsg: " +
            "\nname: " + name.ToString() +
            "\npipeline_id: " + pipeline_id.ToString() +
            "\nplanner_ids: " + System.String.Join(", ", planner_ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
