//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class PlanningSceneMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/PlanningScene";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  name of planning scene
        public string name;
        //  full robot state
        public RobotStateMsg robot_state;
        //  The name of the robot model this scene is for
        public string robot_model_name;
        // additional frames for duplicating tf (with respect to the planning frame)
        public GeometryMessages.TransformStampedMsg[] fixed_frame_transforms;
        // full allowed collision matrix
        public AllowedCollisionMatrixMsg allowed_collision_matrix;
        //  all link paddings
        public LinkPaddingMsg[] link_padding;
        //  all link scales
        public LinkScaleMsg[] link_scale;
        //  Attached objects, collision objects, even the octomap or collision map can have
        //  colors associated to them. This array specifies them.
        public ObjectColorMsg[] object_colors;
        //  the collision map
        public PlanningSceneWorldMsg world;
        //  Flag indicating whether this scene is to be interpreted as a diff with respect to some other scene
        public bool is_diff;

        public PlanningSceneMsg()
        {
            this.name = "";
            this.robot_state = new RobotStateMsg();
            this.robot_model_name = "";
            this.fixed_frame_transforms = new GeometryMessages.TransformStampedMsg[0];
            this.allowed_collision_matrix = new AllowedCollisionMatrixMsg();
            this.link_padding = new LinkPaddingMsg[0];
            this.link_scale = new LinkScaleMsg[0];
            this.object_colors = new ObjectColorMsg[0];
            this.world = new PlanningSceneWorldMsg();
            this.is_diff = false;
        }

        public PlanningSceneMsg(string name, RobotStateMsg robot_state, string robot_model_name, GeometryMessages.TransformStampedMsg[] fixed_frame_transforms, AllowedCollisionMatrixMsg allowed_collision_matrix, LinkPaddingMsg[] link_padding, LinkScaleMsg[] link_scale, ObjectColorMsg[] object_colors, PlanningSceneWorldMsg world, bool is_diff)
        {
            this.name = name;
            this.robot_state = robot_state;
            this.robot_model_name = robot_model_name;
            this.fixed_frame_transforms = fixed_frame_transforms;
            this.allowed_collision_matrix = allowed_collision_matrix;
            this.link_padding = link_padding;
            this.link_scale = link_scale;
            this.object_colors = object_colors;
            this.world = world;
            this.is_diff = is_diff;
        }

        static string[] s_FieldNames = { "name", "robot_state", "robot_model_name", 
            "fixed_frame_transforms", "allowed_collision_matrix", "link_padding", "link_scale", 
            "object_colors", "world", "is_diff" };

        public static PlanningSceneMsg Deserialize(IMessageDeserializer deserializer) => new PlanningSceneMsg(deserializer);

        private PlanningSceneMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.name);
            deserializer.Read(out this.robot_state);
            deserializer.Read(out this.robot_model_name);
            deserializer.Read(out this.fixed_frame_transforms);
            deserializer.Read(out this.allowed_collision_matrix);
            deserializer.Read(out this.link_padding);
            deserializer.Read(out this.link_scale);
            deserializer.Read(out this.object_colors);
            deserializer.Read(out this.world);
            deserializer.Read(out this.is_diff);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.name);
            serializer.Write(this.robot_state);
            serializer.Write(this.robot_model_name);
            serializer.Write(this.fixed_frame_transforms);
            serializer.Write(this.allowed_collision_matrix);
            serializer.Write(this.link_padding);
            serializer.Write(this.link_scale);
            serializer.Write(this.object_colors);
            serializer.Write(this.world);
            serializer.Write(this.is_diff);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "PlanningSceneMsg: " +
            "\nname: " + name.ToString() +
            "\nrobot_state: " + robot_state.ToString() +
            "\nrobot_model_name: " + robot_model_name.ToString() +
            "\nfixed_frame_transforms: " + System.String.Join(", ", fixed_frame_transforms.ToList()) +
            "\nallowed_collision_matrix: " + allowed_collision_matrix.ToString() +
            "\nlink_padding: " + System.String.Join(", ", link_padding.ToList()) +
            "\nlink_scale: " + System.String.Join(", ", link_scale.ToList()) +
            "\nobject_colors: " + System.String.Join(", ", object_colors.ToList()) +
            "\nworld: " + world.ToString() +
            "\nis_diff: " + is_diff.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
