//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class RobotTrajectoryMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/RobotTrajectory";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        public TrajectoryMessages.JointTrajectoryMsg joint_trajectory;
        public TrajectoryMessages.MultiDOFJointTrajectoryMsg multi_dof_joint_trajectory;

        public RobotTrajectoryMsg()
        {
            this.joint_trajectory = new TrajectoryMessages.JointTrajectoryMsg();
            this.multi_dof_joint_trajectory = new TrajectoryMessages.MultiDOFJointTrajectoryMsg();
        }

        public RobotTrajectoryMsg(TrajectoryMessages.JointTrajectoryMsg joint_trajectory, TrajectoryMessages.MultiDOFJointTrajectoryMsg multi_dof_joint_trajectory)
        {
            this.joint_trajectory = joint_trajectory;
            this.multi_dof_joint_trajectory = multi_dof_joint_trajectory;
        }

        static string[] s_FieldNames = { "joint_trajectory", "multi_dof_joint_trajectory" };

        public static RobotTrajectoryMsg Deserialize(IMessageDeserializer deserializer) => new RobotTrajectoryMsg(deserializer);

        private RobotTrajectoryMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.joint_trajectory);
            deserializer.Read(out this.multi_dof_joint_trajectory);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.joint_trajectory);
            serializer.Write(this.multi_dof_joint_trajectory);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "RobotTrajectoryMsg: " +
            "\njoint_trajectory: " + joint_trajectory.ToString() +
            "\nmulti_dof_joint_trajectory: " + multi_dof_joint_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
