//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class ServoStatusMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/ServoStatus";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  Message
        public sbyte code;
        //  will contains integer code
        public string message;
        //  will contain explanatory message
        //  Status types (should reflect StatusCode from moveit_servo/utils/datatype.hpp)
        public const sbyte INVALID = -1;
        public const sbyte NO_WARNING = 0;
        public const sbyte DECELERATE_FOR_APPROACHING_SINGULARITY = 1;
        public const sbyte HALT_FOR_SINGULARITY = 2;
        public const sbyte DECELERATE_FOR_LEAVING_SINGULARITY = 3;
        public const sbyte DECELERATE_FOR_COLLISION = 4;
        public const sbyte HALT_FOR_COLLISION = 5;
        public const sbyte JOINT_BOUND = 6;

        public ServoStatusMsg()
        {
            this.code = 0;
            this.message = "";
        }

        public ServoStatusMsg(sbyte code, string message)
        {
            this.code = code;
            this.message = message;
        }

        static string[] s_FieldNames = { "code", "message" };

        public static ServoStatusMsg Deserialize(IMessageDeserializer deserializer) => new ServoStatusMsg(deserializer);

        private ServoStatusMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.code);
            deserializer.Read(out this.message);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.code);
            serializer.Write(this.message);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "ServoStatusMsg: " +
            "\ncode: " + code.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
