//Do not edit! This file was generated by com.unity.simulationpro MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.SimulationPro.Foundation;

namespace Unity.SimulationPro.Foundation.MoveitMessages
{
    [Serializable]
    public class WorkspaceParametersMsg : IMessage
    {
        public const string k_MessageTypeName = "moveit_msgs/WorkspaceParameters";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        //  This message contains a set of parameters useful in
        //  setting up the volume (a box) in which the robot is allowed to move.
        //  This is useful only when planning for mobile parts of
        //  the robot as well.
        //  Define the frame of reference for the box corners
        public StdMessages.HeaderMsg header;
        //  The minumum corner of the box, with respect to the robot starting pose
        public GeometryMessages.Vector3Msg min_corner;
        //  The maximum corner of the box, with respect to the robot starting pose
        public GeometryMessages.Vector3Msg max_corner;

        public WorkspaceParametersMsg()
        {
            this.header = new StdMessages.HeaderMsg();
            this.min_corner = new GeometryMessages.Vector3Msg();
            this.max_corner = new GeometryMessages.Vector3Msg();
        }

        public WorkspaceParametersMsg(StdMessages.HeaderMsg header, GeometryMessages.Vector3Msg min_corner, GeometryMessages.Vector3Msg max_corner)
        {
            this.header = header;
            this.min_corner = min_corner;
            this.max_corner = max_corner;
        }

        static string[] s_FieldNames = { "header", "min_corner", "max_corner" };

        public static WorkspaceParametersMsg Deserialize(IMessageDeserializer deserializer) => new WorkspaceParametersMsg(deserializer);

        private WorkspaceParametersMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.header);
            deserializer.Read(out this.min_corner);
            deserializer.Read(out this.max_corner);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.header);
            serializer.Write(this.min_corner);
            serializer.Write(this.max_corner);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "WorkspaceParametersMsg: " +
            "\nheader: " + header.ToString() +
            "\nmin_corner: " + min_corner.ToString() +
            "\nmax_corner: " + max_corner.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
