using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class JoystickJointsResult : Message
    {
        public const string RosMessageName = "niryo_one_msgs/JoystickJointsResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  result
        public int has_succeeded { get; set; }

        public JoystickJointsResult()
        {
            this.has_succeeded = 0;
        }

        public JoystickJointsResult(int has_succeeded)
        {
            this.has_succeeded = has_succeeded;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.has_succeeded));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.has_succeeded = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

    }
}
