using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class JoystickJointsFeedback : Message
    {
        public const string RosMessageName = "niryo_one_msgs/JoystickJointsFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  feedback 
        public bool is_in_joints_limit { get; set; }

        public JoystickJointsFeedback()
        {
            this.is_in_joints_limit = false;
        }

        public JoystickJointsFeedback(bool is_in_joints_limit)
        {
            this.is_in_joints_limit = is_in_joints_limit;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.is_in_joints_limit));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.is_in_joints_limit = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

    }
}
