using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class JoystickJointsGoal : Message
    {
        public const string RosMessageName = "niryo_one_msgs/JoystickJointsGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  goal
        public double[] joy_values { get; set; }
        public double duration { get; set; }

        public JoystickJointsGoal()
        {
            this.joy_values = new double[0];
            this.duration = 0.0;
        }

        public JoystickJointsGoal(double[] joy_values, double duration)
        {
            this.joy_values = joy_values;
            this.duration = duration;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(joy_values.Length));
            foreach(var entry in joy_values)
                listOfSerializations.Add(BitConverter.GetBytes(entry));
            listOfSerializations.Add(BitConverter.GetBytes(this.duration));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var joy_valuesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.joy_values= new double[joy_valuesArrayLength];
            for(var i =0; i <joy_valuesArrayLength; i++)
            {
                this.joy_values[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }
            this.duration = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

    }
}
