using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class JoystickJointsAction : Message
    {
        public const string RosMessageName = "niryo_one_msgs/JoystickJointsAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public JoystickJointsActionGoal action_goal { get; set; }
        public JoystickJointsActionResult action_result { get; set; }
        public JoystickJointsActionFeedback action_feedback { get; set; }

        public JoystickJointsAction()
        {
            this.action_goal = new JoystickJointsActionGoal();
            this.action_result = new JoystickJointsActionResult();
            this.action_feedback = new JoystickJointsActionFeedback();
        }

        public JoystickJointsAction(JoystickJointsActionGoal action_goal, JoystickJointsActionResult action_result, JoystickJointsActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(action_goal.SerializationStatements());
            listOfSerializations.AddRange(action_result.SerializationStatements());
            listOfSerializations.AddRange(action_feedback.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.action_goal.Deserialize(data, offset);
            offset = this.action_result.Deserialize(data, offset);
            offset = this.action_feedback.Deserialize(data, offset);

            return offset;
        }

    }
}
