using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.NiryoOne;

namespace RosMessageTypes.NiryoOne
{
    public class RobotMoveGoal : Message
    {
        public const string RosMessageName = "niryo_one_msgs/RobotMoveGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  goal
        public RobotMoveCommand cmd { get; set; }

        public RobotMoveGoal()
        {
            this.cmd = new RobotMoveCommand();
        }

        public RobotMoveGoal(RobotMoveCommand cmd)
        {
            this.cmd = cmd;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(cmd.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.cmd.Deserialize(data, offset);

            return offset;
        }

    }
}
