using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.NiryoOne;

namespace RosMessageTypes.NiryoOne
{
    public class RobotMoveFeedback : Message
    {
        public const string RosMessageName = "niryo_one_msgs/RobotMoveFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  feedback
        public RobotState state { get; set; }

        public RobotMoveFeedback()
        {
            this.state = new RobotState();
        }

        public RobotMoveFeedback(RobotState state)
        {
            this.state = state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(state.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.state.Deserialize(data, offset);

            return offset;
        }

    }
}
