using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class RobotMoveAction : Message
    {
        public const string RosMessageName = "niryo_one_msgs/RobotMoveAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public RobotMoveActionGoal action_goal { get; set; }
        public RobotMoveActionResult action_result { get; set; }
        public RobotMoveActionFeedback action_feedback { get; set; }

        public RobotMoveAction()
        {
            this.action_goal = new RobotMoveActionGoal();
            this.action_result = new RobotMoveActionResult();
            this.action_feedback = new RobotMoveActionFeedback();
        }

        public RobotMoveAction(RobotMoveActionGoal action_goal, RobotMoveActionResult action_result, RobotMoveActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(action_goal.SerializationStatements());
            listOfSerializations.AddRange(action_result.SerializationStatements());
            listOfSerializations.AddRange(action_feedback.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.action_goal.Deserialize(data, offset);
            offset = this.action_result.Deserialize(data, offset);
            offset = this.action_feedback.Deserialize(data, offset);

            return offset;
        }

    }
}
