using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.NiryoOne;

namespace RosMessageTypes.NiryoOne
{
    public class SequenceGoal : Message
    {
        public const string RosMessageName = "niryo_one_msgs/SequenceGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  goal
        public int cmd_type { get; set; }
        public int sequence_id { get; set; }
        public Sequence sequence { get; set; }

        public SequenceGoal()
        {
            this.cmd_type = 0;
            this.sequence_id = 0;
            this.sequence = new Sequence();
        }

        public SequenceGoal(int cmd_type, int sequence_id, Sequence sequence)
        {
            this.cmd_type = cmd_type;
            this.sequence_id = sequence_id;
            this.sequence = sequence;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd_type));
            listOfSerializations.Add(BitConverter.GetBytes(this.sequence_id));
            listOfSerializations.AddRange(sequence.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.cmd_type = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.sequence_id = BitConverter.ToInt32(data, offset);
            offset += 4;
            offset = this.sequence.Deserialize(data, offset);

            return offset;
        }

    }
}
