using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class SequenceAction : Message
    {
        public const string RosMessageName = "niryo_one_msgs/SequenceAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public SequenceActionGoal action_goal { get; set; }
        public SequenceActionResult action_result { get; set; }
        public SequenceActionFeedback action_feedback { get; set; }

        public SequenceAction()
        {
            this.action_goal = new SequenceActionGoal();
            this.action_result = new SequenceActionResult();
            this.action_feedback = new SequenceActionFeedback();
        }

        public SequenceAction(SequenceActionGoal action_goal, SequenceActionResult action_result, SequenceActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(action_goal.SerializationStatements());
            listOfSerializations.AddRange(action_result.SerializationStatements());
            listOfSerializations.AddRange(action_feedback.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.action_goal.Deserialize(data, offset);
            offset = this.action_result.Deserialize(data, offset);
            offset = this.action_feedback.Deserialize(data, offset);

            return offset;
        }

    }
}
