using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.Std;
using RosMessageTypes.Actionlib;

namespace RosMessageTypes.NiryoOne
{
    public class ToolActionFeedback : Message
    {
        public const string RosMessageName = "niryo_one_msgs/ToolActionFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public GoalStatus status { get; set; }
        public ToolFeedback feedback { get; set; }

        public ToolActionFeedback()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.feedback = new ToolFeedback();
        }

        public ToolActionFeedback(Header header, GoalStatus status, ToolFeedback feedback)
        {
            this.header = header;
            this.status = status;
            this.feedback = feedback;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(status.SerializationStatements());
            listOfSerializations.AddRange(feedback.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.status.Deserialize(data, offset);
            offset = this.feedback.Deserialize(data, offset);

            return offset;
        }

    }
}
