using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    public class ToolFeedback : Message
    {
        public const string RosMessageName = "niryo_one_msgs/ToolFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  feedback
        public int progression { get; set; }

        public ToolFeedback()
        {
            this.progression = 0;
        }

        public ToolFeedback(int progression)
        {
            this.progression = progression;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.progression));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.progression = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

    }
}
