#!/bin/bash

help()
{
   echo "Syntax: $0 [part_2|part_3]"
}

source $ROS_WORKSPACE/devel/setup.bash

echo "ROS_IP: $(hostname -i)" > $ROS_WORKSPACE/src/niryo_moveit/config/params.yaml

if [ $1 == "part_2" ]; then
	roslaunch niryo_moveit part_2.launch
elif [ $1 == "part_3" ]; then
	roslaunch niryo_moveit part_3.launch
else
	help
fi
