//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class UnityColor : Message
    {
        public const string RosMessageName = "robotics_demo/UnityColor";

        public int r;
        public int g;
        public int b;
        public int a;

        public UnityColor()
        {
            this.r = 0;
            this.g = 0;
            this.b = 0;
            this.a = 0;
        }

        public UnityColor(int r, int g, int b, int a)
        {
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.r));
            listOfSerializations.Add(BitConverter.GetBytes(this.g));
            listOfSerializations.Add(BitConverter.GetBytes(this.b));
            listOfSerializations.Add(BitConverter.GetBytes(this.a));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.r = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.g = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.b = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.a = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "UnityColor: " +
            "\nr: " + r.ToString() +
            "\ng: " + g.ToString() +
            "\nb: " + b.ToString() +
            "\na: " + a.ToString();
        }
    }
}
