//Do not edit! This file was generated by unity.simulation.foundation MessageGeneration.
#if UNITY_SIMULATION_FOUNDATION
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Simulation.Foundation;

namespace RosMessageTypes.VehicleControllers
{
    [Serializable]
    public class MastMsg : IMessage
    {
        public const string k_MessageTypeName = "vehicle_controllers_msgs/Mast";
        public string MessageTypeName => k_MessageTypeName;
        public static readonly MessageTypeId k_MessageTypeId = new MessageTypeId(k_MessageTypeName);
        public MessageTypeId MessageTypeId => k_MessageTypeId;
        public float mast_vertical_extension;
        //  Total mast extension height
        public float mast_vertical_speed;
        //  Speed at which the mast extends, 0 = as fast as possible
        public float fork_longitudinal_extension;
        //  How far should the fork extend forward
        public float fork_longitudinal_speed;
        //  Speed at which the fork extends forward, 0 = as fast as possible
        public float fork_tilt_target;
        //  Target tilt angle of the fork
        public float fork_tilt_speed;
        //  Speed at which the fork tilt, 0 = as fast as possible
        public float fork_lateral_extension;
        //  Target lateral movement of the fork
        public float fork_lateral_speed;
        //  Speed at which the fork moves laterally, 0 = as fast as possible

        public MastMsg()
        {
            this.mast_vertical_extension = 0.0f;
            this.mast_vertical_speed = 0.0f;
            this.fork_longitudinal_extension = 0.0f;
            this.fork_longitudinal_speed = 0.0f;
            this.fork_tilt_target = 0.0f;
            this.fork_tilt_speed = 0.0f;
            this.fork_lateral_extension = 0.0f;
            this.fork_lateral_speed = 0.0f;
        }

        public MastMsg(float mast_vertical_extension, float mast_vertical_speed, float fork_longitudinal_extension, float fork_longitudinal_speed, float fork_tilt_target, float fork_tilt_speed, float fork_lateral_extension, float fork_lateral_speed)
        {
            this.mast_vertical_extension = mast_vertical_extension;
            this.mast_vertical_speed = mast_vertical_speed;
            this.fork_longitudinal_extension = fork_longitudinal_extension;
            this.fork_longitudinal_speed = fork_longitudinal_speed;
            this.fork_tilt_target = fork_tilt_target;
            this.fork_tilt_speed = fork_tilt_speed;
            this.fork_lateral_extension = fork_lateral_extension;
            this.fork_lateral_speed = fork_lateral_speed;
        }

        static string[] s_FieldNames = { "mast_vertical_extension", "mast_vertical_speed",
            "fork_longitudinal_extension", "fork_longitudinal_speed", "fork_tilt_target",
            "fork_tilt_speed", "fork_lateral_extension", "fork_lateral_speed" };

        public static MastMsg Deserialize(IMessageDeserializer deserializer) => new MastMsg(deserializer);

        private MastMsg(IMessageDeserializer deserializer)
        {
            deserializer.BeginMessage(s_FieldNames);
            deserializer.Read(out this.mast_vertical_extension);
            deserializer.Read(out this.mast_vertical_speed);
            deserializer.Read(out this.fork_longitudinal_extension);
            deserializer.Read(out this.fork_longitudinal_speed);
            deserializer.Read(out this.fork_tilt_target);
            deserializer.Read(out this.fork_tilt_speed);
            deserializer.Read(out this.fork_lateral_extension);
            deserializer.Read(out this.fork_lateral_speed);
            deserializer.EndMessage();
        }

        public void WriteTo(IMessageSerializer serializer)
        {
            serializer.BeginMessage(s_FieldNames);
            serializer.Write(this.mast_vertical_extension);
            serializer.Write(this.mast_vertical_speed);
            serializer.Write(this.fork_longitudinal_extension);
            serializer.Write(this.fork_longitudinal_speed);
            serializer.Write(this.fork_tilt_target);
            serializer.Write(this.fork_tilt_speed);
            serializer.Write(this.fork_lateral_extension);
            serializer.Write(this.fork_lateral_speed);
            serializer.EndMessage();
        }

        public override string ToString()
        {
            return "MastMsg: " +
            "\nmast_vertical_extension: " + mast_vertical_extension.ToString() +
            "\nmast_vertical_speed: " + mast_vertical_speed.ToString() +
            "\nfork_longitudinal_extension: " + fork_longitudinal_extension.ToString() +
            "\nfork_longitudinal_speed: " + fork_longitudinal_speed.ToString() +
            "\nfork_tilt_target: " + fork_tilt_target.ToString() +
            "\nfork_tilt_speed: " + fork_tilt_speed.ToString() +
            "\nfork_lateral_extension: " + fork_lateral_extension.ToString() +
            "\nfork_lateral_speed: " + fork_lateral_speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#endif
        public static void Register()
        {
            MessageTypeRegistry.Register(k_MessageTypeId, Deserialize);
        }
    }
}
#endif
